### ISSUE TITLE
Flask Mpesa Implementation

### ISSUE THREAD

**Issue by KKamaa** [bnjunge/Daraja-API-Complete-Python-Flask-Tutorials#1]
Hello, Like your work and tutorials on Flask and Mpesa you have done a very good job much appreciate it.
I have used your code in testing though the validation and confirmation urls don't pick the response. Any idea what 
can cause that.

**Comment by bnjunge** [comment]
Hello KKamaa, probably you're using URLs or your endpoints aren't reachable from the web. That is the main reason if this happens. This is not an issue though so I will close it.
